version: '3.8'
services:
  db:
    container_name: container-mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
    volumes:
      - db_data:/data/db
    ports:
      - "27017:27017"
  adminer:
    container_name: container-adminer
    image: mongo-express:latest
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_SERVER: db
    ports:
      - "8081:8081"
    depends_on:
      - db
volumes:
  db_data: